name: Common Sound
router_dsn:
    env: ROUTER_DSN
    default: "ws://127.0.0.1:8080/ws"
realm: player
apps:
    - cs
    - playlist
    - monkey
spotify_user:
    env: SPOTIFY_USER
    default: xiris
spotify_password:
    env: SPOTIFY_PASSWORD
playlist:
    env: PLAYLIST
    default: /tmp/playlist.yml
